// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIDCXgAfeDFx24-gUgC94hGJv6yAp6b9o',
    appId: '1:348164550304:web:be2695e85e6167de5c63c5',
    messagingSenderId: '348164550304',
    projectId: 'examen-eab33',
    authDomain: 'examen-eab33.firebaseapp.com',
    storageBucket: 'examen-eab33.appspot.com',
    measurementId: 'G-ZFYWX3YB84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9SP_2nK0bg2iAuvCkxvaMOELBsvnWT7k',
    appId: '1:348164550304:android:1aa02706e86f15a95c63c5',
    messagingSenderId: '348164550304',
    projectId: 'examen-eab33',
    storageBucket: 'examen-eab33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA41gJuIv3ret-Xrsmt_7pic7PFBsGFVyc',
    appId: '1:348164550304:ios:dd942ef6066b45795c63c5',
    messagingSenderId: '348164550304',
    projectId: 'examen-eab33',
    storageBucket: 'examen-eab33.appspot.com',
    iosBundleId: 'com.example.examenMachuca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA41gJuIv3ret-Xrsmt_7pic7PFBsGFVyc',
    appId: '1:348164550304:ios:4c059efba24c2b8c5c63c5',
    messagingSenderId: '348164550304',
    projectId: 'examen-eab33',
    storageBucket: 'examen-eab33.appspot.com',
    iosBundleId: 'com.example.examenMachuca.RunnerTests',
  );
}
